server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eesy_mybatis #你学习mybatis时，使用的数据库地址
    username: root
    password: root
  application:
    name: service-provider #将来会作为微服务的名称
mybatis:
  type-aliases-package: cn.itcast.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka